transport:
  keepAlive: true
  maxIdleConnections: 1000
  maxIdleConnectionsPerHost: 100
  maxConnectionsPerHost: 1000

servers:
  -
    id: "nkc"
    listen: 444
    name:
      - kechuang.org
      - www.kechuang.org
      - it.kechuang.org
    SSLKey: "d:/temp/TLS/www.kechuang.org.key"
    SSLCert: "d:/temp/TLS/www.kechuang.org.crt"
    WEBPass:
      - http://127.0.0.1:9000
    WSPass:
      - http://127.0.0.1:9000
    WEBType: "random"
    WSType: "ipHash"

  -
    id: "nkcRedirect"
    listen: 80
    name:
      - www.kechuang.org
      - kechuang.org
    redirectCode: 301
    redirectUrl: "https://www.kechuang.org"