# 控制台打印
console:
  debug: false
  warning: false
  error: false
  info: false

servers:
  # https
  -
    # 名称
    id: "NKC HTTPS"
    # 端口
    listen: 443
    # 接受的域名
    name:
      - www.kechuang.org
    # ssl
    ssl_key: "/SSL/www.kechuang.org.key"
    ssl_cert: "/SSL/www.kechuang.org.crt"
    # 路径匹配
    location:
      -
        # 路径匹配正则
        reg: "^\\/"
        # 反向代理目标服务
        pass:
          - http://127.0.0.1:9000
          - http://127.0.0.1:9001
          - http://127.0.0.1:9002
          - http://127.0.0.1:9003
        # 负载均衡策略 random（随机）,ip_hash（客户端 IP）
        balance: random
      -
        reg: "^\\/socket.io\\/"
        pass:
          - http://127.0.0.1:10101
        balance: random

  # http 跳转到 https
  -
    id: "NKC HTTP REDIRECT"
    listen: 80
    name:
      - www.kechuang.org
    location:
      -
        reg: "^\\/"
        redirect_code: 301
        redirect_url: "https://www.kechuang.org"
