console:
  debug: false
  warning: false
  error: false
  info: false

proxy: false
maxIpCount: 1

servers:
  -
    listen: 80
    name:
      - location
      - 127.0.0.1
    location:
      -
        reg: "^\\/"
        pass:
          - http://127.0.0.1:8080
        balance: random