transport:
  keepAlive: true
  maxIdleConnections: 1000
  maxIdleConnectionsPerHost: 100
  maxConnectionsPerHost: 1000

servers:
  -
    id: "nkc"
    listen: 444
    name:
      - www.0x0002.com
    SSLKey: "d:/Temp/SSL/www.0x0002.com.key"
    SSLCert: "d:/Temp/SSL/www.0x0002.com.crt"
    WEBPass:
      - http://127.0.0.1:9000
    WSPass:
      - http://127.0.0.1:9000
    WEBType: "random"
    WSType: "ipHash"

  -
    id: "nkcRedirect"
    listen: 90
    name:
      - www.0x0002.com
      - 0x0002.com
    redirectCode: 301
    redirectUrl: "https://www.0x0002.com:444"